project:
  type: book

book:
  title: "Team Project (ADL)"
  author: "Nico Bayer, Buket Kurtulus, Moritz Kick"
  date: "17/01/2025"
  chapters:
    - index.qmd
    - summary.qmd
    - domain.qmd
    - architecture.qmd
    - evaluation.qmd
    - manual.qmd
    - team.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



